name: test
channels:

  - conda-forge

  - defaults
dependencies:
    # Base depends
  - python
  - pip

    # Testing
  - pytest
  - pytest-cov
  - codecov

    # OpenMM
  - openmm
  - pdbfixer

    # Pip-only installs
  - pip:
    - qcelemental
    - git+https://github.com/parmed/parmed.git
    - git+https://github.com/MolSSI/mmic.git
    - git+https://github.com/MolSSI/mmelemental.git
    - git+https://github.com/MolSSI/mmic_translator.git
    - git+https://github.com/MolSSI/mmic_parmed.git
    - git+https://github.com/MolSSI/mmic_pdb.git
